#!/bin/sh
#^^^^^^^^ Just for highlightning. Safe to remove.

#--{ connection settings
#
mpd_host = "localhost"
mpd_port = "6600"
mpd_connection_timeout = "5"
mpd_crossfade_time = "5"

#--{ Delays
#
message_delay_time = "1"
playlist_disable_highlight_delay = "1"


#--{ Display
song_list_format = " $8%a • %t"
song_status_format = "{$3%a$9 $2-$9 {$8%t$9}|{$8%f$9} $5($9$2%b$5)$9} "
song_columns_list_format = "(1f)[black]{l}  (30)[red]{t|f} - (40)[red]{aE:Right}"
song_window_title_format = "[mpd] {%t}|{%f} - {%a}"
song_library_format = "{%n $8-$9 }{%t}|{%f}"

now_playing_prefix = "$b$2 ▶ "
now_playing_suffix = "$8$/b"

selected_item_prefix = "$b  $5"
selected_item_suffix = "$9$/b"



browser_playlist_prefix = "playlist"

### various settings
#execute_on_song_change = ""
playlist_show_remaining_time = "no"
playlist_shorten_total_times = "yes"
playlist_separate_albums = "no"
playlist_display_mode = "columns"
browser_display_mode = "columns"
search_engine_display_mode = "columns"
discard_colors_if_item_is_selected = "no"
incremental_seeking = "yes"
seek_time = "4"
autocenter_mode = "yes"
centered_cursor = "yes"

#progressbar_look = "-|-"
#progressbar_look = "=>"
#progressbar_look = "─- "
#progressbar_look = "▒▒░"
#progressbar_look = "┅┅┄"
#progressbar_look = "─⊙┄"
#progressbar_look = "─➞─"
#progressbar_look = "─┅─"
#progressbar_look = "▪▪▪"
#progressbar_look = "▪▪▫"
#progressbar_look = "───"
#progressbar_look = "▁▁▁"
#progressbar_look = "‒‒‒"
#progressbar_look = "■◣ "
#progressbar_look = "◈◆◇"
#progressbar_look = "██ "
progressbar_look = "━━─"

default_place_to_search_in = "database"
user_interface = "classic"
default_find_mode = "wrapped"
#default_space_mode = "add"
default_tag_editor_pattern = "%n - %t"

header_visibility = "no"
statusbar_visibility = "no"
titles_visibility = "no"

header_text_scrolling = "yes"
cyclic_scrolling = "no"
lines_scrolled = "2"
follow_now_playing_lyrics = "yes"
show_hidden_files_in_local_browser = "no"
jump_to_now_playing_song_at_start = "yes"
clock_display_seconds = "no"
display_volume_level = "yes"
display_bitrate = "no"
display_remaining_time = "no"
regular_expressions = "extended" # (basic/extended)
ignore_leading_the = "no"
block_search_constraints_change_if_items_found = "yes"
mouse_support = "yes"
mouse_list_scroll_whole_page = "yes"

### Visualizer settings
visualizer_fifo_path = "/tmp/mpd.fifo"
visualizer_output_name = "FIFO"
visualizer_sync_interval = "30"
## spectrum / wave
visualizer_type = "spectrum"
visualizer_look = "◆▋"
visualizer_in_stereo = "no"
#visualizer_sample_multipler = 1
visualizer_color = "blue, cyan, green, yellow, magenta, red"


### lyrics support
external_editor = "vim"
use_console_editor = "yes" # (set to yes, if your editor is console app)

colors_enabled = "yes"
empty_tag_color = "white"
header_window_color = "black"
volume_color = "yellow"
state_line_color = "black"
state_flags_color = "black"
main_window_color = "white"
color1 = "white"
color2 = "black"
# main_window_highlight_color = "blue"
progressbar_color = "black"
statusbar_color = "blue"
alternative_ui_separator_color = "black"
#active_column_color = "blue"
current_item_inactive_column_prefix = "red"
current_item_inactive_column_suffix = "red"

window_border_color = "red"
active_window_border = "red"
