#!/bin/sh

dateshow() {
    thedate="$(date "+%I:%M")"
    echo -e " $thedate"
}

# echo "$(vpnstatus) : $(batpercent) : $(dateshow)"
xsetroot -name " $(mpdstatus || spotify-current || echo None) :: $(vpnstatus) :: $(batpercent || echo Cord) :: $(dateshow)"
