#!/bin/sh

dateshow() {
    thedate="$(date "+%I:%M")"
    echo -e " $thedate"
}

# echo "$(vpnstatus) : $(batpercent) : $(dateshow)"
xsetroot -name "$(mpdstatus) :: $(vpnstatus) :: $(batpercent) :: $(dateshow)"
